version: '3'
services:
  db:
    image: mysql:8.0.33-debian
    platform: linux/x86_64
    container_name: wanted-db-deploy
    restart : always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - ./.database.env

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wanted-backend-deploy
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.development
